### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by exodia0x** [mythnc/gbf-bot#14]
Hi, I try to run it but show like this.

Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
===================== RESTART: D:\GBF\gbf-bot-3.1.0\run.py =====================
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\logging\config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "C:\Program Files\Python39\lib\logging\config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GBF\\gbf-bot-3.1.0\\logs\\2021-04-23.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GBF\gbf-bot-3.1.0\gbf_bot\__init__.py", line 37, in <module>
    logging.config.dictConfig(LOGGING)
  File "C:\Program Files\Python39\lib\logging\config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Program Files\Python39\lib\logging\config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'

I used Python 3.9.4 in Windows 10 64bit

**Comment by mythnc** [comment]
https://github.com/mythnc/gbf-bot#notice
